server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: public-service-api
          uri: http://localhost:8080
          predicates:
            - Path=/open-api/**
          filters:
            - RewritePath=/open-api(?<segment>/?.*), $\{segment}
            - ServicePublicApiFilter
